# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiaRwZ3uGoW5S6wIXiyZVARAnbnaUaKG
"""

# -*- coding: utf-8 -*-
"""Séance 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVhRYuSTr4YnxxiblltogqDNiPj2CyLd
"""

#coding:utf8

import pandas as pd
import math
import scipy
import scipy.stats

#C'est la partie la plus importante dans l'analyse de données. D'une part, elle n'est pas simple à comprendre tant mathématiquement que pratiquement. D'autre, elle constitue une application des probabilités. L'idée consiste à comparer une distribution de probabilité (théorique) avec des observations concrètes. De fait, il faut bien connaître les distributions vues dans la séance précédente afin de bien pratiquer cette comparaison. Les probabilités permettent de définir une probabilité critique à partir de laquelle les résultats ne sont pas conformes à la théorie probabiliste.
#Il n'est pas facile de proposer des analyses de données uniquement dans un cadre univarié. Vous utiliserez la statistique inférentielle principalement dans le cadre d'analyses multivariées. La statistique univariée est une statistique descriptive. Bien que les tests y soient possibles, comprendre leur intérêt et leur puissance d'analyse dans un tel cadre peut être déroutant.
#Peu importe dans quelle théorie vous êtes, l'idée de la statistique inférentielle est de vérifier si ce que vous avez trouvé par une méthode de calcul est intelligent ou stupide. Est-ce que l'on peut valider le résultat obtenu ou est-ce que l'incertitude qu'il présente ne permet pas de conclure ? Peu importe également l'outil, à chaque mesure statistique, on vous proposera un test pour vous aider à prendre une décision sur vos résultats. Il faut juste être capable de le lire.

#Par convention, on place les fonctions locales au début du code après les bibliothèques.
def ouvrirUnFichier(nom):
    with open(nom, "r") as fichier:
        contenu = pd.read_csv(fichier)
    return contenu

#Théorie de l'échantillonnage (intervalles de fluctuation)
#L'échantillonnage se base sur la répétitivité.
print("Résultat sur le calcul d'un intervalle de fluctuation")

donnes = pd.DataFrame(ouvrirUnFichier("data/Echantillonnage-100-Echantillons.csv"))

#Théorie de l'estimation (intervalles de confiance)
#L'estimation se base sur l'effectif.
print("Résultat sur le calcul d'un intervalle de confiance")

#Théorie de la décision (tests d'hypothèse)
#La décision se base sur la notion de risques alpha et bêta.
#Comme à la séance précédente, l'ensemble des tests se trouve au lien : https://docs.scipy.org/doc/scipy/reference/stats.html
print("Théorie de la décision")

df1 = pd.read_csv("data/Loi-normale-Test-1.csv", header=None)
df2 = pd.read_csv("data/Loi-normale-Test-2.csv", header=None)

df = pd.read_csv("data/Echantillonnage-100-Echantillons.csv")

# 1: Théorie de l'échantillonnage

moyennes = df.mean()
moyennes_arrondies = moyennes.round(0).astype(int)

print("Moyenne arrondie par colonne :")
print(moyennes_arrondies)

moyennes = df.mean().round(0)
freq_echantillon = (moyennes / moyennes.sum()).round(2)

population = df.sum()
freq_population = (population / population.sum()).round(2)

resultats = pd.DataFrame({
    "Moyenne_arrondie": moyennes,
    "Frequence_echantillon": freq_echantillon,
    "Frequence_population": freq_population
})

print(resultats)

m = df.mean().round(0)
fp = (df.sum() / df.sum().sum()).round(2)
fe = (m / m.sum()).round(2)

z, N = 1.96, df.sum().sum()
s = ((fp * (1 - fp)) / N) ** 0.5

print(pd.DataFrame({
    "Freq_population": fp,
    "Freq_echantillon": fe,
    "Inf_95%": (fp - z * s).round(2),
    "Sup_95%": (fp + z * s).round(2)
}))

# 2: Théorie de l'estimation

echantillon_1 = list(df.iloc[0])

print(echantillon_1)

echantillon = list(df.iloc[0])
total = sum(echantillon)

frequences = [round(x / total, 2) for x in echantillon]

print("Somme de l’échantillon :", total)
print("Fréquences :", frequences)

echantillon = list(df.iloc[0])
N = sum(echantillon)
z = 1.96

frequences = [x / N for x in echantillon]
intervalles = [
    (round(f - z * ((f * (1 - f)) / N) ** 0.5, 2),
     round(f + z * ((f * (1 - f)) / N) ** 0.5, 2))
    for f in frequences
]

for i, intervalle in enumerate(intervalles):
    print(f"Opinion {i+1} : IC 95 % = {intervalle}")

# 3: Théorie de la décision

from scipy.stats import shapiro

d1 = pd.read_csv("data/Loi-normale-Test-1.csv", header=None)
d2 = pd.read_csv("data/Loi-normale-Test-2.csv", header=None)

d1 = pd.to_numeric(d1.iloc[:, 0], errors="coerce").dropna()
d2 = pd.to_numeric(d2.iloc[:, 0], errors="coerce").dropna()

stat1, p1 = shapiro(d1)
stat2, p2 = shapiro(d2)

print("Test 1 -> p-value :", round(p1, 4))
print("Test 2 -> p-value :", round(p2, 4))